/**
 * Application configuration constants
 */

export const AUTH_CONFIG = {
  // Token expiration times (in seconds)
  ACCESS_TOKEN_EXPIRY: 900, // 15 minutes
  REFRESH_TOKEN_EXPIRY: 86400, // 24 hours
  AUTH_CODE_EXPIRY: 300, // 5 minutes
  
  // Challenge expiration
  CHALLENGE_EXPIRY: 300, // 5 minutes
  
  // UI delays (in milliseconds)
  REDIRECT_DELAY: 500,
  LOADING_TIMEOUT: 30000,
  
  // Rate limiting
  MAX_LOGIN_ATTEMPTS: 5,
  RATE_LIMIT_WINDOW: 15 * 60 * 1000, // 15 minutes
  
  // Security
  MIN_SIGNATURE_LENGTH: 64,
  MAX_MESSAGE_LENGTH: 1000,
  MAX_ADDRESS_LENGTH: 100,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR',
} as const;
